name: "Terraform CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-check:
    name: "Lint and Validate"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Format"
        # Checks if your code follows standard alignment/spacing
        run: terraform fmt -check
        working-directory: ./project

      - name: "Terraform Init"
        # Backend is disabled because GitHub doesn't have access to your GCS bucket
        run: terraform init -backend=false
        working-directory: ./project

      - name: "Terraform Validate"
        # Checks for syntax errors, missing variables, or logic flaws
        run: terraform validate
        working-directory: ./project
